/*
 * One-off backfill: give every existing employee an RM/RO tag, a PC code, and a current
 * assignment — derived from the existing `supervisorId` staff hierarchy.
 *
 * Usage:
 *   node src/scripts/backfillPcCodes.js --dry-run   # validate + preview, write nothing
 *   node src/scripts/backfillPcCodes.js             # apply
 *
 * Rules (agreed):
 *   - RM = employee who supervises at least one other employee; RO = everyone else (leaf).
 *   - One PC code per employee, mirroring the supervisor tree: a code reports to the code of
 *     the employee's supervisor. Roots (no/self/missing supervisor) hang under the root 000…0.
 *   - Codes generated by the shared 12-digit / 6-level scheme (pcCodeHelper.nextChildCode).
 *
 * Idempotent: employees that already have an open PC-code assignment are skipped, and RM/RO
 * tags are only set when currently null.
 */
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const { nextChildCode, ROOT_CODE } = require('../helpers/pcCodeHelper');

const DRY = process.argv.includes('--dry-run');

async function main() {
  // Only ACTIVE + APPROVED employees get positions. Terminated/resigned/pending staff must not
  // occupy a seat. A non-active supervisor simply isn't in this set, so their active reports
  // become roots (attach under the root) rather than hanging off a vacated seat.
  const emps = await prisma.employee.findMany({
    where: { lifecycleStatus: 'ACTIVE', approvalStatus: 'APPROVED' },
    select: { id: true, firstName: true, lastName: true, supervisorId: true, rmRoType: true, jobTitleId: true },
  });

  // Positions are named for the ROLE (job title), not the person who holds them. Resolve every
  // referenced job-title id up front so seat creation below is a cheap map lookup.
  const titleIds = [...new Set(emps.map(e => e.jobTitleId).filter(v => v != null).map(Number))];
  const titleRows = titleIds.length
    ? await prisma.codeListValue.findMany({ where: { id: { in: titleIds } }, select: { id: true, label: true } })
    : [];
  const titleById = new Map(titleRows.map(t => [String(t.id), t.label]));
  // Name = job title, or a neutral "Position <code>" when the employee has no title (never a name).
  const seatName = (e, code) => (e.jobTitleId != null && titleById.get(String(e.jobTitleId))) || `Position ${code}`;
  const byId = new Map(emps.map(e => [e.id.toString(), e]));
  const exists = id => id != null && byId.has(id.toString());
  // An employee who reports to themselves is the top of the hierarchy: they OCCUPY the root PC code
  // (000…0) rather than getting a fresh code beneath it. The root is a single seat, so only the first
  // such employee can take it; any others are treated as ordinary roots (placed under the root).
  const selfSupervises = e => e.supervisorId != null && e.supervisorId.toString() === e.id.toString();
  // Ordinary root = no supervisor, or a supervisor who isn't in this active/approved set. These get a
  // new code directly under the synthetic root, as before. Self-supervisors are handled separately.
  const isRoot = e => !selfSupervises(e) && (!e.supervisorId || !exists(e.supervisorId));

  // Pick the single employee who will occupy the root seat (first self-supervisor, by id for
  // determinism). Extras are demoted to ordinary roots and warned about.
  const selfSupervisors = emps.filter(selfSupervises).sort((a, b) => (a.id < b.id ? -1 : 1));
  const rootOccupant = selfSupervisors[0] ?? null;
  const rootOccupantId = rootOccupant ? rootOccupant.id.toString() : null;
  const demotedSelfRoots = selfSupervisors.slice(1).map(e => e.id.toString()); // treated as ordinary roots

  // children map (only among existing employees). The root occupant collects children the same way;
  // demoted self-supervisors and ordinary roots are parents too, just anchored under the synthetic root.
  const childrenOf = new Map();
  for (const e of emps) {
    const id = e.id.toString();
    // The root occupant and ordinary/demoted roots have no *parent* among employees — skip adding
    // them as someone's child. (A self-supervisor's own self-edge must never make them their own child.)
    if (id === rootOccupantId || isRoot(e) || demotedSelfRoots.includes(id)) continue;
    const s = e.supervisorId.toString();
    if (!childrenOf.has(s)) childrenOf.set(s, []);
    childrenOf.get(s).push(id);
  }

  // RM = supervises someone; RO otherwise. The root occupant is always RM (top of the tree).
  const rmSet = new Set(childrenOf.keys());
  if (rootOccupantId) rmSet.add(rootOccupantId);
  const tagOf = id => (rmSet.has(id) ? 'RM' : 'RO');

  // ── Validate the whole tree fits the code scheme BEFORE writing anything ──
  // BFS from roots; a node's code is generated from its parent's code. Throws if a node has
  // >99 children or the chain is deeper than the scheme supports.
  const roots = emps.filter(isRoot).map(e => e.id.toString());
  const codeFor = new Map();            // employeeId -> generated code
  const order = [];                     // DFS order (parents before children)
  const errors = [];

  // Recursively number a parent's children, depth-first, so parents precede children in `order`.
  function assignCodes(parentEmpId, parentCode) {
    const kids = childrenOf.get(parentEmpId) || [];
    const sibCodes = [];
    for (const kid of kids) {
      let code;
      try { code = nextChildCode(parentCode, sibCodes); }
      catch (e) { errors.push(`${label(kid)} under ${label(parentEmpId)}: ${e.message}`); continue; }
      sibCodes.push(code);
      codeFor.set(kid, code);
      order.push(kid);
      assignCodes(kid, code);           // recurse depth-first
    }
  }
  function label(id) { const e = byId.get(id); return e ? `${e.firstName} ${e.lastName} (#${id})` : `#${id}`; }

  // Everything that hangs directly off the synthetic root shares ONE sibling-code list, so their
  // codes don't collide. That set is: the root occupant's own direct reports, plus every ordinary
  // root (no/foreign supervisor) and any demoted extra self-supervisor. They are all siblings under
  // 000…0, whether their "parent" is the occupant or the synthetic root itself.
  const rootSibCodes = [];
  const numberUnderRoot = (rid) => {
    let code;
    try { code = nextChildCode(ROOT_CODE, rootSibCodes); }
    catch (e) { errors.push(`${label(rid)} (under root): ${e.message}`); return; }
    rootSibCodes.push(code);
    codeFor.set(rid, code);
    order.push(rid);
    assignCodes(rid, code);        // number this node's own subtree with its private sibling list
  };

  // The self-supervising employee OCCUPIES the root code itself; place them first, then their direct
  // reports (as root-children), so parents precede children in `order`.
  if (rootOccupantId) {
    codeFor.set(rootOccupantId, ROOT_CODE);
    order.push(rootOccupantId);
    for (const kid of (childrenOf.get(rootOccupantId) || [])) numberUnderRoot(kid);
  }

  // Ordinary roots + demoted self-supervisors: also direct children of the synthetic root.
  for (const rid of [...roots, ...demotedSelfRoots]) numberUnderRoot(rid);

  // Employees never reached from a root are inside a supervisor cycle — reported and skipped
  // (agreed: these are test/system accounts; assign by hand later if needed).
  const skipped = emps.filter(e => !codeFor.has(e.id.toString()));

  const rmCount = emps.filter(e => tagOf(e.id.toString()) === 'RM').length;
  console.log(`Employees              : ${emps.length}`);
  console.log(`  root occupant        : ${rootOccupant ? label(rootOccupantId) + '  → ' + ROOT_CODE : '(none — no self-supervising employee)'}`);
  console.log(`  roots (under root)   : ${roots.length + demotedSelfRoots.length}`);
  console.log(`  RM (has reports)     : ${rmCount}`);
  console.log(`  RO (leaf)            : ${emps.length - rmCount}`);
  console.log(`Codes generated        : ${codeFor.size}`);
  if (demotedSelfRoots.length) {
    console.log(`⚠ Multiple self-supervising employees — only the first occupies the root; these were placed under it:`);
    demotedSelfRoots.forEach(id => console.log(`   - ${label(id)}`));
  }
  if (skipped.length) {
    console.log(`Skipped (supervisor cycle): ${skipped.length}`);
    skipped.forEach(e => console.log(`   - ${e.firstName} ${e.lastName} (#${e.id})`));
  }
  if (errors.length) {
    console.log(`\n❌ ${errors.length} employees do NOT fit the code scheme:`);
    errors.slice(0, 20).forEach(e => console.log('   - ' + e));
    if (errors.length > 20) console.log(`   … and ${errors.length - 20} more`);
    console.log('\nAborting — widen the scheme or flatten these branches first. Nothing was written.');
    process.exit(1);
  }
  console.log('✔ All employees fit the code scheme.');

  // Sample preview
  console.log('\nSample (first 8):');
  order.slice(0, 8).forEach(id => console.log(`   ${codeFor.get(id)}  ${tagOf(id).padEnd(2)}  ${label(id)}`));

  if (DRY) { console.log('\n[dry-run] No changes written.'); await prisma.$disconnect(); return; }

  // ── Apply ──
  // Skip employees that already hold a PC code (idempotent re-run).
  const alreadyAssigned = new Set(
    (await prisma.pccodeassignments.findMany({ where: { endDate: null }, select: { employeeId: true } }))
      .map(a => a.employeeId.toString())
  );

  let codesCreated = 0, assignmentsCreated = 0, tagsSet = 0;
  // Insert parents before children (order[] is already parent-first) so reportsToId resolves.
  const empToCodeRow = new Map();       // employeeId -> pccodes.id
  const rootRow = await prisma.pccodes.findFirst({ where: { reportsToId: null } });

  for (const id of order) {
    const e = byId.get(id);
    const tag = tagOf(id);

    // RM/RO tag (only when unset)
    if (!e.rmRoType) {
      await prisma.employee.update({ where: { id: BigInt(id) }, data: { rmRoType: tag } });
      tagsSet++;
    }

    if (alreadyAssigned.has(id)) continue; // keep existing placement

    // The root occupant takes over the EXISTING synthetic root row instead of creating a new code —
    // relabel it (by job title) and assign them to it. Their children then report to this same row.
    if (id === rootOccupantId) {
      await prisma.pccodes.update({
        where: { id: rootRow.id },
        data:  { name: seatName(e, ROOT_CODE), isActive: true },
      });
      empToCodeRow.set(id, rootRow.id);
      await prisma.pccodeassignments.create({
        data: { pcCodeId: rootRow.id, employeeId: BigInt(id), startDate: new Date(), endDate: null },
      });
      assignmentsCreated++;
      continue;
    }

    // Parent code: the employee's supervisor's code, or the root row for ordinary/demoted roots.
    const parentEmpId = (isRoot(e) || demotedSelfRoots.includes(id)) ? null : e.supervisorId.toString();
    const reportsToId = parentEmpId ? (empToCodeRow.get(parentEmpId) ?? rootRow.id) : rootRow.id;

    const codeRow = await prisma.pccodes.create({
      data: { code: codeFor.get(id), name: seatName(e, codeFor.get(id)), reportsToId, isActive: true },
    });
    empToCodeRow.set(id, codeRow.id);
    codesCreated++;

    await prisma.pccodeassignments.create({
      data: { pcCodeId: codeRow.id, employeeId: BigInt(id), startDate: new Date(), endDate: null },
    });
    assignmentsCreated++;
  }

  console.log(`\n✅ Backfill complete:`);
  console.log(`   RM/RO tags set      : ${tagsSet}`);
  console.log(`   PC codes created    : ${codesCreated}`);
  console.log(`   assignments created : ${assignmentsCreated}`);
  await prisma.$disconnect();
}

main().catch(async e => { console.error('❌ backfill failed:', e.message); await prisma.$disconnect(); process.exit(1); });
