/*
 * Backfill: give every existing employee an RM/RO tag, a PC code, and a current
 * assignment — derived from the existing `supervisorId` staff hierarchy.
 *
 * Usage:
 *   node src/scripts/backfillPcCodes.js --dry-run   # validate + preview, write nothing
 *   node src/scripts/backfillPcCodes.js             # apply
 *
 * Also run automatically by the migration loader (helpers/migration/migrationLoader.js) as its
 * "PC codes" step, against whichever database the migration targets.
 *
 * Rules (agreed):
 *   - RM = employee who supervises at least one other employee; RO = everyone else (leaf).
 *   - One PC code per employee, mirroring the supervisor tree: a code reports to the code of
 *     the employee's supervisor. Roots (no/self/missing supervisor) hang under the root 000…0.
 *   - Codes generated by the shared 12-digit / 6-level scheme (pcCodeHelper.nextChildCode).
 *
 * Idempotent: employees that already have an open PC-code assignment are skipped, and RM/RO
 * tags are only set when currently null.
 *
 * Writes are BATCHED (a handful of statements in total, not ~3 per employee): the migration
 * target is a remote database at ~550ms round-trip, where per-row writes took ~30 minutes.
 */
const { PrismaClient } = require('@prisma/client');
const { nextChildCode, ROOT_CODE } = require('../helpers/pcCodeHelper');

const BATCH = 500;

// Staff codes left out of the PC-code tree entirely. UTB is a separate unit whose own chain of
// command ends at two staff who have resigned (UTB00001, UTB00006), so none of its 352 staff connect
// to the bank's hierarchy — and placing them all at the top would overflow the 99-per-level scheme.
// Agreed: UTB positions are set up separately, by hand. Override with PC_CODE_EXCLUDE_PREFIXES
// (comma-separated; set it to an empty string to include everyone).
const EXCLUDED_PREFIXES = (process.env.PC_CODE_EXCLUDE_PREFIXES ?? 'UTB')
  .split(',').map(s => s.trim()).filter(Boolean);

/**
 * Work out every employee's code and tag from the supervisor tree. Pure — reads nothing, writes
 * nothing — so the dry run and the real run cannot disagree.
 */
function planPcCodes(emps, titleById) {
  const seatName = (e, code) => (e.jobTitleId != null && titleById.get(String(e.jobTitleId))) || `Position ${code}`;
  const byId = new Map(emps.map(e => [e.id.toString(), e]));
  const exists = id => id != null && byId.has(id.toString());
  // An employee who reports to themselves is the top of the hierarchy: they OCCUPY the root PC code
  // (000…0) rather than getting a fresh code beneath it. The root is a single seat, so only the first
  // such employee can take it; any others are treated as ordinary roots (placed under the root).
  const selfSupervises = e => e.supervisorId != null && e.supervisorId.toString() === e.id.toString();
  // Ordinary root = no supervisor, or a supervisor who isn't in this active/approved set.
  const isRoot = e => !selfSupervises(e) && (!e.supervisorId || !exists(e.supervisorId));

  const selfSupervisors = emps.filter(selfSupervises).sort((a, b) => (a.id < b.id ? -1 : 1));
  const rootOccupantId = selfSupervisors[0] ? selfSupervisors[0].id.toString() : null;
  const demotedSelfRoots = selfSupervisors.slice(1).map(e => e.id.toString());

  const childrenOf = new Map();
  for (const e of emps) {
    const id = e.id.toString();
    if (id === rootOccupantId || isRoot(e) || demotedSelfRoots.includes(id)) continue;
    const s = e.supervisorId.toString();
    if (!childrenOf.has(s)) childrenOf.set(s, []);
    childrenOf.get(s).push(id);
  }

  // RM = supervises someone; RO otherwise. The root occupant is always RM (top of the tree).
  const rmSet = new Set(childrenOf.keys());
  if (rootOccupantId) rmSet.add(rootOccupantId);
  const tagOf = id => (rmSet.has(id) ? 'RM' : 'RO');

  const label = id => { const e = byId.get(id); return e ? `${e.firstName} ${e.lastName} (#${id})` : `#${id}`; };
  const codeFor = new Map();     // employeeId -> generated code
  const parentOf = new Map();    // employeeId -> parent employeeId (null = the synthetic root)
  const order = [];              // parents before children
  const errors = [];

  function assignCodes(parentEmpId, parentCode) {
    const sibCodes = [];
    for (const kid of childrenOf.get(parentEmpId) || []) {
      let code;
      try { code = nextChildCode(parentCode, sibCodes); }
      catch (err) { errors.push(`${label(kid)} under ${label(parentEmpId)}: ${err.message}`); continue; }
      sibCodes.push(code);
      codeFor.set(kid, code);
      parentOf.set(kid, parentEmpId);
      order.push(kid);
      assignCodes(kid, code);
    }
  }

  // Everything hanging directly off the root shares ONE sibling list so their codes don't collide:
  // the root occupant's direct reports, every ordinary root, and any demoted self-supervisor.
  const rootSibCodes = [];
  const numberUnderRoot = (rid, parentEmpId) => {
    let code;
    try { code = nextChildCode(ROOT_CODE, rootSibCodes); }
    catch (err) { errors.push(`${label(rid)} (under root): ${err.message}`); return; }
    rootSibCodes.push(code);
    codeFor.set(rid, code);
    parentOf.set(rid, parentEmpId);
    order.push(rid);
    assignCodes(rid, code);
  };

  if (rootOccupantId) {
    codeFor.set(rootOccupantId, ROOT_CODE);
    parentOf.set(rootOccupantId, null);
    order.push(rootOccupantId);
    for (const kid of childrenOf.get(rootOccupantId) || []) numberUnderRoot(kid, rootOccupantId);
  }
  const roots = emps.filter(isRoot).map(e => e.id.toString());
  for (const rid of [...roots, ...demotedSelfRoots]) numberUnderRoot(rid, null);

  // Never reached from a root = inside a supervisor cycle; reported and left for manual assignment.
  const skipped = emps.filter(e => !codeFor.has(e.id.toString()));

  return {
    byId, order, codeFor, parentOf, tagOf, seatName, label, errors, skipped,
    rootOccupantId, demotedSelfRoots, rootCount: roots.length + demotedSelfRoots.length,
    rmCount: emps.filter(e => tagOf(e.id.toString()) === 'RM').length,
  };
}

/**
 * Run the backfill against a database.
 *
 * @param {object}  [opts]
 * @param {string}  [opts.url]     connection string; omitted → the app's own database (PG_URL)
 * @param {boolean} [opts.dryRun]  plan and validate only
 * @param {boolean} [opts.quiet]   suppress console output (the migration reports its own notes)
 * @returns {Promise<object>} counts — throws on a tree that does not fit the code scheme
 */
async function backfillPcCodes({ url, dryRun = false, quiet = false } = {}) {
  const log = quiet ? () => {} : console.log;
  const prisma = url ? new PrismaClient({ datasources: { db: { url } } }) : new PrismaClient();
  try {
    // Only ACTIVE + APPROVED employees get positions. Terminated/resigned/pending staff must not
    // occupy a seat. A non-active supervisor simply isn't in this set, so their active reports
    // become roots (attach under the root) rather than hanging off a vacated seat.
    // Excluded units (see EXCLUDED_PREFIXES) are left out here, so they get no seat and no RM/RO tag
    // — and anyone reporting to one of their staff is treated like any other employee whose
    // supervisor is outside the set (placed under the root).
    const emps = await prisma.employee.findMany({
      where: {
        lifecycleStatus: 'ACTIVE', approvalStatus: 'APPROVED',
        ...(EXCLUDED_PREFIXES.length ? {
          OR: [
            { employee_id: null },
            { AND: EXCLUDED_PREFIXES.map(pre => ({ NOT: { employee_id: { startsWith: pre, mode: 'insensitive' } } })) },
          ],
        } : {}),
      },
      select: { id: true, firstName: true, lastName: true, supervisorId: true, rmRoType: true, jobTitleId: true },
    });
    const excludedCount = EXCLUDED_PREFIXES.length
      ? await prisma.employee.count({
          where: { lifecycleStatus: 'ACTIVE', approvalStatus: 'APPROVED',
                   OR: EXCLUDED_PREFIXES.map(pre => ({ employee_id: { startsWith: pre, mode: 'insensitive' } })) },
        })
      : 0;

    // Positions are named for the ROLE (job title), never the person who holds them.
    const titleIds = [...new Set(emps.map(e => e.jobTitleId).filter(v => v != null).map(Number))];
    const titleRows = titleIds.length
      ? await prisma.codeListValue.findMany({ where: { id: { in: titleIds } }, select: { id: true, label: true } })
      : [];
    const titleById = new Map(titleRows.map(t => [String(t.id), t.label]));

    const p = planPcCodes(emps, titleById);

    if (excludedCount) log(`Excluded (${EXCLUDED_PREFIXES.join(', ')} staff codes): ${excludedCount}`);
    log(`Employees              : ${emps.length}`);
    log(`  root occupant        : ${p.rootOccupantId ? p.label(p.rootOccupantId) + '  → ' + ROOT_CODE : '(none — no self-supervising employee)'}`);
    log(`  roots (under root)   : ${p.rootCount}`);
    log(`  RM (has reports)     : ${p.rmCount}`);
    log(`  RO (leaf)            : ${emps.length - p.rmCount}`);
    log(`Codes generated        : ${p.codeFor.size}`);
    if (p.demotedSelfRoots.length) {
      log('⚠ Multiple self-supervising employees — only the first occupies the root; these were placed under it:');
      p.demotedSelfRoots.forEach(id => log(`   - ${p.label(id)}`));
    }
    if (p.skipped.length) {
      log(`Skipped (supervisor cycle): ${p.skipped.length}`);
      p.skipped.forEach(e => log(`   - ${e.firstName} ${e.lastName} (#${e.id})`));
    }
    if (p.errors.length) {
      const msg = `${p.errors.length} employees do not fit the PC-code scheme (e.g. ${p.errors[0]}) — nothing was written`;
      log(`\n❌ ${msg}`);
      p.errors.slice(0, 20).forEach(e => log('   - ' + e));
      throw new Error(msg);
    }
    log('✔ All employees fit the code scheme.');
    log('\nSample (first 8):');
    p.order.slice(0, 8).forEach(id => log(`   ${p.codeFor.get(id)}  ${p.tagOf(id).padEnd(2)}  ${p.label(id)}`));

    const result = {
      employees: emps.length, excluded: excludedCount, excludedPrefixes: EXCLUDED_PREFIXES,
      rm: p.rmCount, ro: emps.length - p.rmCount,
      skippedCycle: p.skipped.length, tagsSet: 0, codesCreated: 0, assignmentsCreated: 0,
      alreadyAssigned: 0, note: null,
    };
    if (dryRun) { log('\n[dry-run] No changes written.'); return result; }

    // ── Apply ──
    // Existing open assignments: those employees keep their placement, and their seat is reused as
    // the parent for any of their reports that still need one.
    const openRows = await prisma.pccodeassignments.findMany({
      where: { endDate: null }, select: { employeeId: true, pcCodeId: true },
    });
    const seatOf = new Map(openRows.map(a => [a.employeeId.toString(), a.pcCodeId]));
    const todo = p.order.filter(id => !seatOf.has(id));
    result.alreadyAssigned = p.order.length - todo.length;

    // RM/RO tags — only where unset. Two statements, not one per employee.
    for (const tag of ['RM', 'RO']) {
      const ids = p.order.filter(id => p.tagOf(id) === tag && !p.byId.get(id).rmRoType).map(BigInt);
      for (let i = 0; i < ids.length; i += BATCH) {
        const r = await prisma.employee.updateMany({
          where: { id: { in: ids.slice(i, i + BATCH) }, rmRoType: null }, data: { rmRoType: tag },
        });
        result.tagsSet += r.count;
      }
    }
    if (!todo.length) { log('\nEvery employee already holds a PC code — nothing to create.'); return result; }

    // The generated codes assume a tree built from scratch. If some codes already exist (staff placed
    // by hand, or a partial earlier run) new ones could collide with seats someone else holds, so
    // stop rather than guess — those employees can be placed from the PC Codes screen.
    const wanted = todo.filter(id => id !== p.rootOccupantId).map(id => p.codeFor.get(id));
    const clashes = wanted.length
      ? await prisma.pccodes.findMany({ where: { code: { in: wanted } }, select: { code: true } })
      : [];
    if (clashes.length) {
      result.note = `${todo.length} employees still need a PC code, but ${clashes.length} of the generated codes already exist ` +
        `(e.g. ${clashes[0].code}) — not created automatically; assign them from the PC Codes screen`;
      log(`\n⚠ ${result.note}`);
      return result;
    }

    // The root seat. Seeded by the pccodes manual migration, but created here if missing so a fresh
    // database still gets a complete tree.
    let rootRow = await prisma.pccodes.findFirst({ where: { reportsToId: null } });
    if (!rootRow) {
      rootRow = await prisma.pccodes.create({ data: { code: ROOT_CODE, name: 'Root', reportsToId: null, isActive: true } });
    }

    // The root occupant takes over the EXISTING root row rather than getting a new code.
    if (p.rootOccupantId && todo.includes(p.rootOccupantId)) {
      await prisma.pccodes.update({
        where: { id: rootRow.id },
        data:  { name: p.seatName(p.byId.get(p.rootOccupantId), ROOT_CODE), isActive: true },
      });
      seatOf.set(p.rootOccupantId, rootRow.id);
    }

    // 1. Create every new seat in bulk (parents linked in step 2, once all ids exist).
    const newSeats = todo.filter(id => id !== p.rootOccupantId)
      .map(id => ({ code: p.codeFor.get(id), name: p.seatName(p.byId.get(id), p.codeFor.get(id)), isActive: true }));
    for (let i = 0; i < newSeats.length; i += BATCH) {
      const r = await prisma.pccodes.createMany({ data: newSeats.slice(i, i + BATCH) });
      result.codesCreated += r.count;
    }
    const created = await prisma.pccodes.findMany({
      where: { code: { in: newSeats.map(s => s.code) } }, select: { id: true, code: true },
    });
    const rowByCode = new Map(created.map(r => [r.code, r.id]));
    for (const id of todo) if (id !== p.rootOccupantId) seatOf.set(id, rowByCode.get(p.codeFor.get(id)));

    // 2. Link each new seat to its supervisor's seat (or the root) — one UPDATE per batch.
    const links = todo.filter(id => id !== p.rootOccupantId).map(id => {
      const parentEmp = p.parentOf.get(id);
      return { seat: seatOf.get(id), parent: (parentEmp && seatOf.get(parentEmp)) || rootRow.id };
    });
    for (let i = 0; i < links.length; i += BATCH) {
      const chunk = links.slice(i, i + BATCH);
      const vals = chunk.map((_, j) => `($${j * 2 + 1}::bigint, $${j * 2 + 2}::bigint)`).join(',');
      await prisma.$executeRawUnsafe(
        `UPDATE pccodes c SET reportstoid = v.parent FROM (VALUES ${vals}) AS v(seat, parent) WHERE c.id = v.seat`,
        ...chunk.flatMap(l => [l.seat, l.parent]));
    }

    // 3. Seat each employee.
    const now = new Date();
    const assignments = todo.map(id => ({ pcCodeId: seatOf.get(id), employeeId: BigInt(id), startDate: now, endDate: null }));
    for (let i = 0; i < assignments.length; i += BATCH) {
      const r = await prisma.pccodeassignments.createMany({ data: assignments.slice(i, i + BATCH) });
      result.assignmentsCreated += r.count;
    }

    log('\n✅ Backfill complete:');
    log(`   RM/RO tags set      : ${result.tagsSet}`);
    log(`   PC codes created    : ${result.codesCreated}`);
    log(`   assignments created : ${result.assignmentsCreated}`);
    return result;
  } finally {
    await prisma.$disconnect();
  }
}

module.exports = { backfillPcCodes, planPcCodes };

// CLI
if (require.main === module) {
  backfillPcCodes({ dryRun: process.argv.includes('--dry-run') })
    .catch(e => { console.error('❌ backfill failed:', e.message); process.exit(1); });
}
