/*
 * One-off backfill: give every existing employee an RM/RO tag, a PC code, and a current
 * assignment — derived from the existing `supervisorId` staff hierarchy.
 *
 * Usage:
 *   node src/scripts/backfillPcCodes.js --dry-run   # validate + preview, write nothing
 *   node src/scripts/backfillPcCodes.js             # apply
 *
 * Rules (agreed):
 *   - RM = employee who supervises at least one other employee; RO = everyone else (leaf).
 *   - One PC code per employee, mirroring the supervisor tree: a code reports to the code of
 *     the employee's supervisor. Roots (no/self/missing supervisor) hang under the root 000…0.
 *   - Codes generated by the shared 12-digit / 6-level scheme (pcCodeHelper.nextChildCode).
 *
 * Idempotent: employees that already have an open PC-code assignment are skipped, and RM/RO
 * tags are only set when currently null.
 */
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const { nextChildCode, ROOT_CODE } = require('../helpers/pcCodeHelper');

const DRY = process.argv.includes('--dry-run');

async function main() {
  // Only ACTIVE + APPROVED employees get positions. Terminated/resigned/pending staff must not
  // occupy a seat. A non-active supervisor simply isn't in this set, so their active reports
  // become roots (attach under the root) rather than hanging off a vacated seat.
  const emps = await prisma.employee.findMany({
    where: { lifecycleStatus: 'ACTIVE', approvalStatus: 'APPROVED' },
    select: { id: true, firstName: true, lastName: true, supervisorId: true, rmRoType: true },
  });
  const byId = new Map(emps.map(e => [e.id.toString(), e]));
  const exists = id => id != null && byId.has(id.toString());
  const isRoot = e => !e.supervisorId || e.supervisorId.toString() === e.id.toString() || !exists(e.supervisorId);

  // children map (only among existing employees)
  const childrenOf = new Map();
  for (const e of emps) {
    if (isRoot(e)) continue;
    const s = e.supervisorId.toString();
    if (!childrenOf.has(s)) childrenOf.set(s, []);
    childrenOf.get(s).push(e.id.toString());
  }

  // RM = supervises someone; RO otherwise.
  const rmSet = new Set(childrenOf.keys());
  const tagOf = id => (rmSet.has(id) ? 'RM' : 'RO');

  // ── Validate the whole tree fits the code scheme BEFORE writing anything ──
  // BFS from roots; a node's code is generated from its parent's code. Throws if a node has
  // >99 children or the chain is deeper than the scheme supports.
  const roots = emps.filter(isRoot).map(e => e.id.toString());
  const codeFor = new Map();            // employeeId -> generated code
  const order = [];                     // DFS order (parents before children)
  const errors = [];

  // Recursively number a parent's children, depth-first, so parents precede children in `order`.
  function assignCodes(parentEmpId, parentCode) {
    const kids = childrenOf.get(parentEmpId) || [];
    const sibCodes = [];
    for (const kid of kids) {
      let code;
      try { code = nextChildCode(parentCode, sibCodes); }
      catch (e) { errors.push(`${label(kid)} under ${label(parentEmpId)}: ${e.message}`); continue; }
      sibCodes.push(code);
      codeFor.set(kid, code);
      order.push(kid);
      assignCodes(kid, code);           // recurse depth-first
    }
  }
  function label(id) { const e = byId.get(id); return e ? `${e.firstName} ${e.lastName} (#${id})` : `#${id}`; }

  // Root employees are direct children of the synthetic root code.
  const rootSibCodes = [];
  for (const rid of roots) {
    let code;
    try { code = nextChildCode(ROOT_CODE, rootSibCodes); }
    catch (e) { errors.push(`${label(rid)} (root): ${e.message}`); continue; }
    rootSibCodes.push(code);
    codeFor.set(rid, code);
    order.push(rid);
    assignCodes(rid, code);
  }

  // Employees never reached from a root are inside a supervisor cycle — reported and skipped
  // (agreed: these are test/system accounts; assign by hand later if needed).
  const skipped = emps.filter(e => !codeFor.has(e.id.toString()));

  const rmCount = emps.filter(e => tagOf(e.id.toString()) === 'RM').length;
  console.log(`Employees              : ${emps.length}`);
  console.log(`  roots (under root)   : ${roots.length}`);
  console.log(`  RM (has reports)     : ${rmCount}`);
  console.log(`  RO (leaf)            : ${emps.length - rmCount}`);
  console.log(`Codes generated        : ${codeFor.size}`);
  if (skipped.length) {
    console.log(`Skipped (supervisor cycle): ${skipped.length}`);
    skipped.forEach(e => console.log(`   - ${e.firstName} ${e.lastName} (#${e.id})`));
  }
  if (errors.length) {
    console.log(`\n❌ ${errors.length} employees do NOT fit the code scheme:`);
    errors.slice(0, 20).forEach(e => console.log('   - ' + e));
    if (errors.length > 20) console.log(`   … and ${errors.length - 20} more`);
    console.log('\nAborting — widen the scheme or flatten these branches first. Nothing was written.');
    process.exit(1);
  }
  console.log('✔ All employees fit the code scheme.');

  // Sample preview
  console.log('\nSample (first 8):');
  order.slice(0, 8).forEach(id => console.log(`   ${codeFor.get(id)}  ${tagOf(id).padEnd(2)}  ${label(id)}`));

  if (DRY) { console.log('\n[dry-run] No changes written.'); await prisma.$disconnect(); return; }

  // ── Apply ──
  // Skip employees that already hold a PC code (idempotent re-run).
  const alreadyAssigned = new Set(
    (await prisma.pccodeassignments.findMany({ where: { endDate: null }, select: { employeeId: true } }))
      .map(a => a.employeeId.toString())
  );

  let codesCreated = 0, assignmentsCreated = 0, tagsSet = 0;
  // Insert parents before children (order[] is already parent-first) so reportsToId resolves.
  const empToCodeRow = new Map();       // employeeId -> pccodes.id
  const rootRow = await prisma.pccodes.findFirst({ where: { reportsToId: null } });

  for (const id of order) {
    const e = byId.get(id);
    const tag = tagOf(id);

    // RM/RO tag (only when unset)
    if (!e.rmRoType) {
      await prisma.employee.update({ where: { id: BigInt(id) }, data: { rmRoType: tag } });
      tagsSet++;
    }

    if (alreadyAssigned.has(id)) continue; // keep existing placement

    const parentEmpId = isRoot(e) ? null : e.supervisorId.toString();
    const reportsToId = parentEmpId ? (empToCodeRow.get(parentEmpId) ?? rootRow.id) : rootRow.id;

    const codeRow = await prisma.pccodes.create({
      data: { code: codeFor.get(id), name: `${e.firstName} ${e.lastName}`.trim() || codeFor.get(id), reportsToId, isActive: true },
    });
    empToCodeRow.set(id, codeRow.id);
    codesCreated++;

    await prisma.pccodeassignments.create({
      data: { pcCodeId: codeRow.id, employeeId: BigInt(id), startDate: new Date(), endDate: null },
    });
    assignmentsCreated++;
  }

  console.log(`\n✅ Backfill complete:`);
  console.log(`   RM/RO tags set      : ${tagsSet}`);
  console.log(`   PC codes created    : ${codesCreated}`);
  console.log(`   assignments created : ${assignmentsCreated}`);
  await prisma.$disconnect();
}

main().catch(async e => { console.error('❌ backfill failed:', e.message); await prisma.$disconnect(); process.exit(1); });
